/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.scsu.anonymous;

import static com.scsu.anonymous.MeetingPassword.PlainTextPassword;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Swathi
 */
public class ChatHome extends javax.swing.JFrame {

    public ChatModel chatModel = new ChatModel();
    PasswordEncrypt pwdEncrypt = new PasswordEncrypt();
    String uname;
    String meetNum;

    /**
     * Creates new form ChatHome
     */
    public ChatHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pwdSubmit = new javax.swing.JButton();
        MeetingPwd = new javax.swing.JPasswordField();
        MeetingNum = new javax.swing.JTextField();
        meetingpwd = new javax.swing.JLabel();
        meetingNum = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SubmitBtn1 = new javax.swing.JButton();
        GetPwdBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        Meeting = new javax.swing.JLabel();
        MeetingCipher = new javax.swing.JTextField();
        PlainText = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pwdSubmit.setText("Submit");
        pwdSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdSubmitActionPerformed(evt);
            }
        });

        MeetingNum.setEditable(false);
        MeetingNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeetingNumActionPerformed(evt);
            }
        });

        meetingpwd.setText("Meeting Password");

        meetingNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        meetingNum.setText("Meeting #");

        username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username.setText("Username");

        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Welcome..!");

        SubmitBtn1.setText("Submit");
        SubmitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtn1ActionPerformed(evt);
            }
        });

        GetPwdBtn.setText("Get Meeting Password");
        GetPwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetPwdBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        Meeting.setText("Meting Cipher");

        HomeBtn.setText("Home");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(249, 249, 249)
                                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(meetingNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Meeting)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(meetingpwd)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pwdSubmit)
                                    .addComponent(MeetingPwd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                    .addComponent(MeetingNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                    .addComponent(GetPwdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MeetingCipher, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(3, 224, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SubmitBtn1)
                                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(HomeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(PlainText, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(HomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(SubmitBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MeetingNum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meetingNum))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MeetingCipher, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Meeting))
                .addGap(30, 30, 30)
                .addComponent(GetPwdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(PlainText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MeetingPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meetingpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwdSubmit)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdSubmitActionPerformed
        // TODO add your handling code here:
        String password = String.valueOf(MeetingPwd.getPassword());
        String MeetNum = MeetingNum.getText();
        String resp = chatModel.checkPassword(MeetNum, password);
        if (resp.equalsIgnoreCase("SUCCESS")) {
            dispose();
            Chat chat;
            new Chat().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Please enter a valid password");
            MeetingPwd.setText("");
        }


    }//GEN-LAST:event_pwdSubmitActionPerformed

    private void SubmitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtn1ActionPerformed
        // TODO add your handling code here:
        String uname = Username.getText();
        String cmpval = Authentication.UserName.getText();

        if (uname == null || uname == "" || uname.isEmpty()) {
            JOptionPane.showMessageDialog(jPanel1, "Please enter Username");
            Username.setText("");
        } else if (cmpval.equals(uname)) {
            if (uname.matches("^.*[@stcloudstate.edu]{1}$")) {
                java.util.Date currentTimeStamp = new java.util.Date();
                System.out.println("currentTimeStamp  " + currentTimeStamp);
                java.sql.Timestamp timeStamp = new java.sql.Timestamp(currentTimeStamp.getTime());
                System.out.println("timeStamp  " + timeStamp);
                String resp = chatModel.checkParticipant(uname, timeStamp);
                System.out.println("timeStamp  " + timeStamp);
                if (resp.equalsIgnoreCase("FAILURE")) {
                    text.setText("You don't have any meetings at this time. Please come back again.");
                    MeetingNum.setText("");
                } else {
                    text.setText("Please enter the meeting password");
                    MeetingNum.setText(resp);
                }
            } else {
                JOptionPane.showMessageDialog(jPanel1, "Please enter a valid Username");
            }
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Please enter your username");
        }
    }//GEN-LAST:event_SubmitBtn1ActionPerformed

    private void MeetingNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeetingNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MeetingNumActionPerformed

    private void GetPwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPwdBtnActionPerformed
        // TODO add your handling code here:
        uname = Username.getText();
        meetNum = MeetingNum.getText();
        String Key;
        String Quotient;
        String plainText = null;
        String cipher = MeetingCipher.getText();
        String resp = chatModel.checkCipher(uname, cipher, meetNum);

        if (resp.equalsIgnoreCase("SUCCESS")) {
            char[] Cipher = cipher.toCharArray();
            int len = Cipher.length;
            char[] PlainText = new char[len];
            int input;
            Key = chatModel.getKey(uname, meetNum);
            if (!Key.equalsIgnoreCase("FAILURE")) {
                char[] key = Key.toCharArray();
                for (int j = 0; j < key.length; j++) {
                    System.out.println("KKEy : " + key[j]);
                }
                Quotient = chatModel.getQuotient(uname, meetNum);
                if (!Quotient.equalsIgnoreCase("FAILURE")) {
                    char[] quotient = Quotient.toCharArray();
                    for (int j = 0; j < quotient.length; j++) {
                        System.out.println("Qquotient : " + quotient[j]);
                    }
                    for (int i = 0; i < len; i++) {
                        input = (int) Cipher[i] + 32;
                        input = (input - ((int) key[i] - 48)) + (94 * ((int) quotient[i] - 48));
                        input = input - 32;
                        PlainText[i] = (char) input;

                    }
                    plainText = Arrays.toString(PlainText);
                    System.out.println("PPPlainText:  " + plainText);
                    plainText = plainText.replace("[", "");
                    plainText = plainText.replace("]", "");
                    plainText = plainText.replace(", ", "");
                    System.out.println("PlainText:  " + plainText);

                }
            }
        }
        PlainText.setText(plainText);

    }//GEN-LAST:event_GetPwdBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        Authentication.UserName.setText("");
        Authentication.Name.setText("");
        Authentication.Designation.setText("");
        dispose();
        new Start().setVisible(true);
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
        String cmpval = Authentication.Designation.getText();
        System.out.println("qwerty:  "+cmpval);
        if(cmpval.equals("Manager")){
            dispose();
            new ManagerHome().setVisible(true);
        } else if(cmpval.equals("Employee")){
            dispose();
            new EmployeeHome().setVisible(true); 
        }
    }//GEN-LAST:event_HomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetPwdBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JLabel Meeting;
    private javax.swing.JTextField MeetingCipher;
    public static javax.swing.JTextField MeetingNum;
    private javax.swing.JPasswordField MeetingPwd;
    private javax.swing.JLabel PlainText;
    private javax.swing.JButton SubmitBtn1;
    public static javax.swing.JTextField Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel meetingNum;
    private javax.swing.JLabel meetingpwd;
    private javax.swing.JButton pwdSubmit;
    private javax.swing.JLabel text;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

}
